### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by KRKNUK** [KRKNUK/krknuk.github.io#2]
- [ ] Add copy to main section
- [ ] Look into Jekyll formatting
- [ ] Create technical articles
